// <auto-generated />
using System;
using AnnuaireEntrepriseCESI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnnuaireEntrepriseCESI.Migrations
{
    [DbContext(typeof(AnnuaireEntrepriseDbContext))]
    [Migration("20220305151027_InsertSeedService")]
    partial class InsertSeedService
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnnuaireEntrepriseCESI.Data.Models.Employe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CellPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FixePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Employe");
                });

            modelBuilder.Entity("AnnuaireEntrepriseCESI.Data.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdc32c8b-336d-4056-b526-d5abb7c8f7da"),
                            Name = "Service Commercial"
                        },
                        new
                        {
                            Id = new Guid("d4801915-8a73-4093-9570-ce0f29ebafd2"),
                            Name = "Service Marketing"
                        },
                        new
                        {
                            Id = new Guid("44f46e77-ad56-4b38-a4eb-7c48a111cef3"),
                            Name = "Service Financier"
                        },
                        new
                        {
                            Id = new Guid("e87bd3af-26ee-4ccd-9919-ad0795a4ddbd"),
                            Name = "Service Industriel"
                        },
                        new
                        {
                            Id = new Guid("848b1c6c-6bed-4e43-ae08-677e95210c98"),
                            Name = "Service Ressources Humaines"
                        },
                        new
                        {
                            Id = new Guid("f15ae25b-a93e-4ac7-8fbb-ba9e526c1bb0"),
                            Name = "Service Achat"
                        },
                        new
                        {
                            Id = new Guid("33ed3c1d-01b9-4390-8516-d2ed7e306ee9"),
                            Name = "Service Juridique"
                        });
                });

            modelBuilder.Entity("AnnuaireEntrepriseCESI.Data.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Site");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d11a4470-e264-4a40-932e-8f3212dd8a54"),
                            Description = "Site administratif",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("d4b7f9d7-9559-47ad-a8ba-da5dbe72b620"),
                            Description = "Site de Production",
                            Name = "Nantes"
                        },
                        new
                        {
                            Id = new Guid("cbda5772-33de-4450-8f9d-22d2775afd6b"),
                            Description = "Site de Production",
                            Name = "Toulouse"
                        },
                        new
                        {
                            Id = new Guid("cd8f7cf6-900f-47cf-97ff-fdf72eaa6029"),
                            Description = "Site de Production",
                            Name = "Nice"
                        },
                        new
                        {
                            Id = new Guid("9216e2ef-9dca-4a5c-960a-7986c7044fb8"),
                            Description = "Site de Production",
                            Name = "Lille"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
